services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres-data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    ports:
      - "9090:8080"

volumes:
  postgres-data:
